Repository getindata/terraform-snowflake-database-role, pull requests merged in 2024-07, with the labels that each got.

#4 feat: Snowflake db role
  README.md
  examples/complete/.env.dist
  examples/complete/README.md
  examples/complete/fixtures.tfvars
  examples/complete/main.tf
  examples/complete/outputs.tf
  examples/complete/providers.tf
  examples/complete/versions.tf
  examples/simple/.env.dist
  examples/simple/README.md
  examples/simple/main.tf
  examples/simple/outputs.tf
  examples/simple/providers.tf
  examples/simple/versions.tf
  locals.tf
  main.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: release/major

#6 feat: Add missing functionalities / options
  .pre-commit-config.yaml
  .terraform-docs.yml
  README.md
  examples/complete/README.md
  examples/complete/main.tf
  examples/complete/versions.tf
  examples/simple/README.md
  examples/simple/versions.tf
  main.tf
  variables.tf
  versions.tf
Labels: release/minor

#7 fix: Add conditional null to database-role-name
  .pre-commit-config.yaml
  .tflint.hcl
  locals.tf
Labels: release/patch
